# Generated by Django 4.2.14 on 2024-07-13 03:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apod',
            fields=[
                ('apod_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='APODタイトル')),
                ('explanation', models.TextField(blank=True, verbose_name='APOD説明')),
                ('date', models.DateField(verbose_name='APODリクエスト日')),
                ('url', models.URLField(blank=True, verbose_name='APODURL')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='論理削除')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, verbose_name='ユーザー名')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='論理削除')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('like_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delete_flg', models.BooleanField(default=False, verbose_name='論理削除')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('apod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacePick_app.apod', verbose_name='APODID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacePick_app.users', verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='Apod_vote',
            fields=[
                ('apod_vote_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_flg', models.BooleanField(default=False, verbose_name='投票フラグ')),
                ('vote_date', models.DateTimeField(verbose_name='投票日時')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('apod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacePick_app.apod', verbose_name='APODID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacePick_app.users', verbose_name='ユーザーID')),
            ],
        ),
    ]
